### ISSUE TITLE
DateTime->date: The field is required.

### ISSUE THREAD

**Issue by MasterPuffin** [chiiya/laravel-passes#22]
I use the following code to create a validTimeInterval in an EventTicketObject
```
validTimeInterval: new TimeInterval(
		start: new DateTime(date: Carbon::now()),
		end: new DateTime(Carbon::now()->addMonth())
	),
```
However the following error message appears
```
PHP Fatal error:  Uncaught Spatie\DataTransferObject\Exceptions\ValidationException: Validation errors:
	 - `Chiiya\Passes\Google\Components\Common\DateTime->date`: The field is required. in /var/www/GoogleWalletDemo/vendor/spatie/data-transfer-object/src/Reflection/DataTransferObjectClass.php:63
Stack trace:
#0 /var/www/GoogleWalletDemo/vendor/spatie/data-transfer-object/src/DataTransferObject.php(38): Spatie\DataTransferObject\Reflection\DataTransferObjectClass->validate()
#1 /var/www/GoogleWalletDemo/src/google_event.php(91): Spatie\DataTransferObject\DataTransferObject->__construct()
#2 {main}
  thrown in /var/www/GoogleWalletDemo/vendor/spatie/data-transfer-object/src/Reflection/DataTransferObjectClass.php on line 63
```

**Comment by chiiya** [comment]
For your `end` date, you didn't define a `date` property. It should be:

```php
validTimeInterval: new TimeInterval(
    start: new DateTime(date: Carbon::now()),
    end: new DateTime(date: Carbon::now()->addMonth())
),
```
